### ISSUE TITLE
The Tool is not producing intended result

### ISSUE THREAD

**Issue by sn1p3rt3s7** [hakluke/hakoriginfinder#14]
Hi,

* **Command**:
`prips 93.184.215.0/28 | ./hakoriginfinder -h http://example.com/index.html | grep -v "NOMATCH"`

![image](https://github.com/hakluke/hakoriginfinder/assets/28353619/97d175ea-a145-43f5-8f25-04b9e54d2365)
![image](https://github.com/hakluke/hakoriginfinder/assets/28353619/24153845-d555-4800-8b6f-74607adcc582)
**Issue**: Matching all the IP addresses given in 93.184.215.0/24 range

The expected output should be
`MATCH` for `93.184.215.14` and `NOMATCH` for others

**Comment by all3njk** [comment]
Looks like all the other IP addresses in the subnet range accept the host header and loads example.com page. All part of same Organization :thinking:

**Comment by hakluke** [comment]
Hey, this is working exactly as intended.

If you check manually with curl, the response from all of these IPs with the `Host` header set to `example.com` is identical to the response of navigating to `example.com` directly.

Here's a diff to prove it:

```
/$ diff <(curl -s -H "Host: example.com" 93.184.215.11) <(curl -s example.com)
/$ diff <(curl -s -H "Host: example.com" 93.184.215.10) <(curl -s example.com)
/$
```
