### ISSUE TITLE
support of https

### ISSUE THREAD

**Issue by alonek1** [hakluke/hakoriginfinder#2]
hi,
Why the tool doesn't support https request as an initial point instead of http?
many sites behind the waf doesn't support http at all and it is forced to use ssl tunnel (through HSTS).

best regards.

**Comment by hakluke** [comment]
Yeah I should update it... currently it just submits to http://*, but most hosts would redirect to https anyway which would still work provided the origin host does the redirect via a Location header to the HTTPS url. Feel free to submit a PR to update it.

**Comment by hakluke** [comment]
Yeah it would be good to give the option, feel free to submit a PR... I'll get around to it eventually but it may be months/years if I'm honest.

Also note that currently if HTTP redirects to HTTPS, it will still work.

**Comment by hakluke** [comment]
Actually nevermind, it was fixed in #1
