### ISSUE TITLE
Maybe change MATCH to SUCCESS or something similar?

### ISSUE THREAD

**Issue by 6mile** [hakluke/hakoriginfinder#9]
Hakluke,
Great tool mate!   I'm creating a GitHub issue to run something past you before I make a PR.

Just a thought though...  maybe we could change the word "MATCH" to something like "SUCCESS" or "HIT" or whatever.  My thinking is that a different word stands out and is simpler from a regex perspective to grok through the many lines of "NOMATCH" just to find the one "MATCH".   That one "MATCH" line doesn't pop, whereas if we changed it to "SUCCESS" or "HIT" or "BOOYA" or whatever, it would pop more.

**Comment by hakluke** [comment]
Yeah I like this - I'm just worried that changing it now will break people's automation. I guess people will just need to `grep -v NOMATCH` or `grep -e '^MATCH'`
